include("counting/count_occurences.jl")
include("histograms/value_histogram.jl")
include("permutation_ordinal/symbolic.jl")
include("kernel/kernel_density.jl")
include("timescales/timescales.jl")
include("transfer_operator/transfer_operator.jl")
include("dispersion/dispersion.jl")
include("diversity/diversity.jl")
