testfile("kozachenkoleonenko.jl")
testfile("kraskov.jl")
testfile("zhu.jl")
testfile("zhusingh.jl")
testfile("alizadeharghami.jl")
testfile("correa.jl")
testfile("ebrahimi.jl")
testfile("vasicek.jl")
