include("fasthist.jl")
include("rectangular_binning.jl")
include("gaussian_cdf.jl")
include("ordinal_pattern.jl")
include("relative_mean_encoding.jl")
include("relative_first_difference_encoding.jl")
include("combination_encoding.jl")
