include("fasthist.jl")
include("rectangular_binning.jl")
include("gaussian_cdf.jl")
include("ordinal_pattern.jl")
include("amplitude_encoding.jl")
include("firstdifference_encoding.jl")
include("combination_encoding.jl")
